//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products
    {
        public int Id { get; set; }
        public string Product { get; set; }
        public int Cost { get; set; }
        public short Age { get; set; }
        public string Dimensions { get; set; }
        public Nullable<int> Count { get; set; }
        public Nullable<int> Weigth { get; set; }
        public string Notes { get; set; }
    }
}
